version: '3'
services:
  gateway:
    build: ../api-gateway/nginx/
    image: api-gateway
    networks:
      - backend
      - frontend
    depends_on:
      - workflow-block-service
      - forms-editor-service
      - frontend
      - workflow-editor-service
      - case-executor-service
    ports:
    - '8080:80'

  workflow-block-service:
    build: ../workflow-block-service
    image: workflow-block-service
    env_file:
        - ./.env
    networks:
      - backend

  workflow-editor-service:
    build: ../workflow-editor-service
    image: workflow-editor-service
    networks:
      - backend
      - workflow-editor
    depends_on:
      - workflow-editor-datastore
  workflow-editor-datastore:
    image: mongo:3.0.2
    networks:
      - workflow-editor

  case-executor-service:
    build:
      context: ../case-executor-service
      dockerfile: manager/Dockerfile
    image: case-executor-service
    networks:
      - backend
      - case-executor
    depends_on:
      - case-executor-datastore
  case-executor-worker:
    build:
      context: ../case-executor-service
      dockerfile: worker/Dockerfile
    image: case-executor-worker
    networks:
      - case-executor
      - backend
    depends_on:
      - case-executor-datastore
  case-executor-datastore:
    image: mongo:3.0.2
    networks:
      - case-executor

  forms-editor-service:
    build: ../forms-editor-service
    image: forms-editor-service
    networks:
      - backend

  frontend:
    build: ../frontend
    image: frontend
    networks:
      - frontend
networks:
  backend:
  frontend:
  workflow-editor:
  case-executor:
