version: '3'
services:
  gateway:
    build: ../api-gateway/nginx/
    image: api-gateway
    networks:
      - backend
      - frontend
    depends_on:
      - workflow-block-service
      - forms-editor-service
      - frontend
      - workflow-editor-service
    ports:
    - '8080:80'
  workflow-block-service:
    build: ../workflow-block-service
    image: workflow-block-service
    networks:
      - backend
  workflow-editor-service:
    build: ../workflow-editor-service
    image: workflow-editor-service
    networks:
      - backend
      - workflow-editor
    depends_on:
      - workflow-editor-datastore
  workflow-editor-datastore:
    image: mongo:3.0.2
    networks:
      - workflow-editor
  forms-editor-service:
    build: ../forms-editor-service
    image: forms-editor-service
    networks:
      - backend
  frontend:
    build: ../frontend
    image: frontend
    networks:
      - frontend
networks:
  backend:
  frontend:
  workflow-editor: